px4ctrl:
  ros__parameters:
    ctrl_freq_max: 100.0
    max_manual_vel: 2.0
    frame_id: map
    use_bodyrate_ctrl: false

    topics:
      rc: /mavros/rc/in
      odom: /mavros/local_position/odom
      imu: /mavros/imu/data
      cmd: /position_cmd
      takeoff_land: /px4ctrl/takeoff_land
      setpoint: /mavros/setpoint_raw/attitude
      simulink_setpoint: /px4ctrl/simulink/attitude_target
      simulink_reference: /px4ctrl/simulink/reference_state
      simulink_actual: /px4ctrl/simulink/actual_state
      simulink_tracking_error: /px4ctrl/simulink/tracking_error
      simulink_ude_debug: /px4ctrl/simulink/ude_debug
      ude_tune: /px4ctrl/ude_tune
      ude_tune_status: /px4ctrl/ude_tune_status
      ude_tune_status_text: /px4ctrl/ude_tune_status_text
      expert_pose: /px4ctrl/expert_pose
      gripper_command: /gripper/command
      traj_start_trigger: /traj_start_trigger
      state: /mavros/state
      extended_state: /mavros/extended_state
      battery: /mavros/battery
    services:
      set_mode: /mavros/set_mode
      arming: /mavros/cmd/arming
      command: /mavros/cmd/command

    msg_timeout:
      odom: 0.5
      imu: 0.5
      rc: 0.5
      cmd: 0.5
      bat: 0.5

    rc_reverse:
      roll: false
      pitch: true
      yaw: false
      throttle: true

    auto_takeoff_land:
      enable: true
      enable_auto_arm: true
      no_RC: false
      takeoff_height: 1.0
      takeoff_land_speed: 0.2

    limits:
      x_min: -7.0
      x_max: 14.0
      y_min: -2.5
      y_max: 2.5
      z_min: -0.3
      z_max: 2.5

    gripper:
      rc_channel: 10
      pwm_open: 1300
      pwm_close: 1700
      open_position: 100.0
      closed_position: 0.0
      force_open_below_z: 0.20

    cmd_feedforward:
      enable: false
      max_velocity: 4.0
      max_acceleration: 5.0

    td:
      enable: true
      r_diag: [2.0, 2.0, 2.0]

    controller:
      gravity: 9.81
      max_angle_deg: 45.0
      max_bodyrate_x: 5.0
      max_bodyrate_y: 5.0
      max_bodyrate_z: 5.0
      min_thrust: 0.05
      max_thrust: 0.90

    ude:
      Kp_diag: [0.5,0.8,2.5]
      Kd_diag: [1.0,1.3,1.8]
      T_diag: [0.4, 0.4, 0.1]
      max_f_hat: [5.0, 5.0, 5.0]
      max_u_acc: [5.0, 5.0, 5.0]

    attitude:
      KAng_diag: [6.0, 6.0, 3.0]

    thrust_model:
      hover_thrust: 0.33
      enable_estimation: true
      print_value: false
      rho2: 0.990
      min_thr2acc: 2.0
      max_thr2acc: 50.0

feetech_gripper_node:
  ros__parameters:
    command_topic: /gripper/command
    command_pair_topic: /gripper/command_pair
    feedback_topic: /gripper/feedback
    feedback_rate_hz: 20.0
    port: /dev/ttyACM1
    left_id: 1
    right_id: 2
    left_inverted: true
    right_inverted: true
    torque_limit: 0
    goal_velocity: 0
    acceleration: 0
    open_on_shutdown: true
    shutdown_open_position: 100.0
    shutdown_open_repeats: 3
    no_configure: false
    dry_run: false
    lerobot_src: /home/user/vla_drone/lerobot/src
