<?xml version="1.0"?>
<package format="3">
  <name>uav_utils</name>
  <version>0.0.0</version>
  <description>Header-only utility functions for the VLADrone px4ctrl ROS2 port.</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>LGPLv3</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>eigen3_cmake_module</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
