#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

START_STACK="${START_STACK:-true}"
START_PX4CTRL="${START_PX4CTRL:-true}"
PX4CTRL_GRIPPER_RC_CHANNEL="${PX4CTRL_GRIPPER_RC_CHANNEL:-0}"
PX4CTRL_TAKEOFF_LAND_SPEED="${PX4CTRL_TAKEOFF_LAND_SPEED:-0.35}"
PX4CTRL_TAKEOFF_HEIGHT="${PX4CTRL_TAKEOFF_HEIGHT:-}"
PX4CTRL_UDE_ENABLE="${PX4CTRL_UDE_ENABLE:-}"
PX4CTRL_TD_ENABLE="${PX4CTRL_TD_ENABLE:-}"
PX4CTRL_CMD_FEEDFORWARD_ENABLE="${PX4CTRL_CMD_FEEDFORWARD_ENABLE:-}"
PX4CTRL_ATTITUDE_FEEDBACK_MODE="${PX4CTRL_ATTITUDE_FEEDBACK_MODE:-}"
TRAJ_PLANNER_ENABLE="${TRAJ_PLANNER_ENABLE:-false}"
TRAJ_PLANNER_INPUT_TOPIC="${TRAJ_PLANNER_INPUT_TOPIC:-/position_cmd_raw}"
TRAJ_PLANNER_OUTPUT_TOPIC="${TRAJ_PLANNER_OUTPUT_TOPIC:-/position_cmd_traj}"
TRAJ_PLANNER_RATE_HZ="${TRAJ_PLANNER_RATE_HZ:-50.0}"
TRAJ_PLANNER_MAX_SPEED_XY_MPS="${TRAJ_PLANNER_MAX_SPEED_XY_MPS:-${MAX_SPEED:-0.30}}"
TRAJ_PLANNER_MAX_ACCEL_XY_MPS2="${TRAJ_PLANNER_MAX_ACCEL_XY_MPS2:-0.35}"
TRAJ_PLANNER_MAX_SPEED_Z_MPS="${TRAJ_PLANNER_MAX_SPEED_Z_MPS:-0.15}"
TRAJ_PLANNER_MAX_ACCEL_Z_MPS2="${TRAJ_PLANNER_MAX_ACCEL_Z_MPS2:-0.25}"
TRAJ_PLANNER_CENTERING_MAX_SPEED_XY_MPS="${TRAJ_PLANNER_CENTERING_MAX_SPEED_XY_MPS:-0.10}"
TRAJ_PLANNER_CENTERING_MAX_ACCEL_XY_MPS2="${TRAJ_PLANNER_CENTERING_MAX_ACCEL_XY_MPS2:-0.20}"
TRAJ_PLANNER_MAX_YAW_RATE_RADPS="${TRAJ_PLANNER_MAX_YAW_RATE_RADPS:-0.35}"
TRAJ_PLANNER_MAX_YAW_ACCEL_RADPS2="${TRAJ_PLANNER_MAX_YAW_ACCEL_RADPS2:-0.50}"
TRAJ_PLANNER_GOAL_REPLAN_POS_THRESHOLD_M="${TRAJ_PLANNER_GOAL_REPLAN_POS_THRESHOLD_M:-0.005}"
TRAJ_PLANNER_GOAL_REPLAN_YAW_THRESHOLD_RAD="${TRAJ_PLANNER_GOAL_REPLAN_YAW_THRESHOLD_RAD:-0.02}"
TRAJ_PLANNER_GOAL_STALE_TIMEOUT_S="${TRAJ_PLANNER_GOAL_STALE_TIMEOUT_S:-0.5}"
TRAJ_PLANNER_DURATION_SCALE="${TRAJ_PLANNER_DURATION_SCALE:-1.05}"
STACK_STARTUP_WAIT_S="${STACK_STARTUP_WAIT_S:-8}"
WAIT_FOR_ENTER="${WAIT_FOR_ENTER:-false}"
CONFIRM_BEFORE_TAKEOFF="${CONFIRM_BEFORE_TAKEOFF:-true}"
TAKEOFF_MODE="${TAKEOFF_MODE:-auto}"
KEEP_STACK_ON_INTERRUPT="${KEEP_STACK_ON_INTERRUPT:-false}"
CLEANUP_STACK_ON_EXIT="${CLEANUP_STACK_ON_EXIT:-true}"
STACK_CLEANUP_TIMEOUT_S="${STACK_CLEANUP_TIMEOUT_S:-5}"
STACK_PID_FILE="${STACK_PID_FILE:-}"

VRPN_SOURCE_TOPIC="${VRPN_SOURCE_TOPIC:-/vla_drone1/pose}"
MAVROS_VISION_TOPIC="${MAVROS_VISION_TOPIC:-/mavros/vision_pose/pose}"
TARGET_POSE_TOPIC="${TARGET_POSE_TOPIC:-/strawberry_bear/pose}"
BOX_POSE_TOPIC="${BOX_POSE_TOPIC:-/box1/pose}"
DRONE_POSE_TOPIC="${DRONE_POSE_TOPIC:-/mavros/local_position/odom}"
ARRIVAL_POSE_TOPIC="${ARRIVAL_POSE_TOPIC:-/mavros/vision_pose/pose}"
CMD_TOPIC="${CMD_TOPIC:-/position_cmd}"
RC_TOPIC="${RC_TOPIC:-/mavros/rc/in}"
PX4CTRL_STATE_TOPIC="${PX4CTRL_STATE_TOPIC:-/px4ctrl/state}"
MAVROS_STATE_TOPIC="${MAVROS_STATE_TOPIC:-/mavros/state}"
POSE_PREFLIGHT_TIMEOUT_S="${POSE_PREFLIGHT_TIMEOUT_S:-6}"
POSE_PREFLIGHT_RETRIES="${POSE_PREFLIGHT_RETRIES:-3}"
POSE_PREFLIGHT_REQUIRED="${POSE_PREFLIGHT_REQUIRED:-true}"
SKIP_POSE_PREFLIGHT="${SKIP_POSE_PREFLIGHT:-false}"
PREFLIGHT_CHECKER="${PREFLIGHT_CHECKER:-${WORKSPACE_DIR}/src/px4ctrl/scripts/topic_liveness_check.py}"
PREFLIGHT_PYTHON="${PREFLIGHT_PYTHON:-/usr/bin/python3}"
PREFLIGHT_STATUS_LOG_PERIOD_S="${PREFLIGHT_STATUS_LOG_PERIOD_S:-0.0}"

GRIPPER_MANAGER_PORT="${GRIPPER_MANAGER_PORT:-/dev/ttyACM1}"
HLS_GRAVITY_COMP_PATH="${HLS_GRAVITY_COMP_PATH:-${WORKSPACE_DIR}/install/hls_gripper/share/hls_gripper/config/gravity_compensation.json}"
HLS_MOTION_PROFILE="${HLS_MOTION_PROFILE:-p0}"
HLS_SEARCH_SPEED="${HLS_SEARCH_SPEED:-}"
HLS_SEARCH_ACC="${HLS_SEARCH_ACC:-}"
HLS_SEARCH_TORQUE_LIMIT="${HLS_SEARCH_TORQUE_LIMIT:-}"
HLS_LEFT_CURRENT_INWARD_SIGN="${HLS_LEFT_CURRENT_INWARD_SIGN:-1}"
HLS_RIGHT_CURRENT_INWARD_SIGN="${HLS_RIGHT_CURRENT_INWARD_SIGN:-1}"
HLS_OPEN_TORQUE_LIMIT="${HLS_OPEN_TORQUE_LIMIT:-160}"
HLS_LOW_CURRENT="${HLS_LOW_CURRENT:-28}"
HLS_CENTER_HOLD_CURRENT="${HLS_CENTER_HOLD_CURRENT:-24}"
HLS_CENTER_PUSH_CURRENT="${HLS_CENTER_PUSH_CURRENT:-115}"
HLS_GRIP_CHASE_MIN_CURRENT="${HLS_GRIP_CHASE_MIN_CURRENT:-36}"
HLS_LIFT_CURRENT="${HLS_LIFT_CURRENT:-1000}"
HLS_MAX_CURRENT="${HLS_MAX_CURRENT:-1700}"
HLS_GRIP_CHASE_POSITION_ENABLE="${HLS_GRIP_CHASE_POSITION_ENABLE:-true}"
HLS_GRIP_CHASE_POSITION_SPEED="${HLS_GRIP_CHASE_POSITION_SPEED:-5}"
HLS_GRIP_CHASE_POSITION_ACC="${HLS_GRIP_CHASE_POSITION_ACC:-2}"
HLS_GRIP_CHASE_POSITION_TORQUE_LIMIT="${HLS_GRIP_CHASE_POSITION_TORQUE_LIMIT:-80}"
HLS_GRIP_CHASE_SLIP_RATIO="${HLS_GRIP_CHASE_SLIP_RATIO:-0.03}"
HLS_GRIP_CHASE_POSITION_PERIOD_S="${HLS_GRIP_CHASE_POSITION_PERIOD_S:-0.50}"
HLS_GRIP_CHASE_POSITION_PULSE_S="${HLS_GRIP_CHASE_POSITION_PULSE_S:-0.15}"
HLS_CENTER_TIMEOUT_ACTION="${HLS_CENTER_TIMEOUT_ACTION:-final_grip}"
HLS_CENTER_TIMEOUT_S="${HLS_CENTER_TIMEOUT_S:-3.0}"
HLS_CENTER_STABLE_TIME_S="${HLS_CENTER_STABLE_TIME_S:-0.30}"
HLS_FINAL_GRIP_RAMP_S="${HLS_FINAL_GRIP_RAMP_S:-0.8}"
HLS_CENTER_ERROR_GAIN="${HLS_CENTER_ERROR_GAIN:-2.0}"
HLS_CONTACT_CURRENT_THRESHOLD="${HLS_CONTACT_CURRENT_THRESHOLD:-40.0}"
HLS_CONTACT_EXIT_THRESHOLD="${HLS_CONTACT_EXIT_THRESHOLD:-18.0}"
HLS_CONTACT_STRONG_THRESHOLD="${HLS_CONTACT_STRONG_THRESHOLD:-65.0}"
HLS_CONTACT_CONFIRM_CYCLES="${HLS_CONTACT_CONFIRM_CYCLES:-2}"
HLS_SEARCH_CONTACT_CURRENT_THRESHOLD="${HLS_SEARCH_CONTACT_CURRENT_THRESHOLD:-50.0}"
HLS_SEARCH_CONTACT_STRONG_THRESHOLD="${HLS_SEARCH_CONTACT_STRONG_THRESHOLD:-175.0}"
HLS_SEARCH_CONTACT_CONFIRM_CYCLES="${HLS_SEARCH_CONTACT_CONFIRM_CYCLES:-3}"
HLS_SEARCH_CONTACT_MIN_CLOSE_RATIO="${HLS_SEARCH_CONTACT_MIN_CLOSE_RATIO:-0.12}"
HLS_SINGLE_CONTACT_OFFSET_LIMIT_M="${HLS_SINGLE_CONTACT_OFFSET_LIMIT_M:-0.12}"
HLS_MANAGER_STARTUP_TIMEOUT_S="${HLS_MANAGER_STARTUP_TIMEOUT_S:-5.0}"

RC_TIMEOUT_S="${RC_TIMEOUT_S:-2.0}"
RC_STALE_ACTION="${RC_STALE_ACTION:-warn}"
CH10_INDEX="${CH10_INDEX:-9}"
CH10_OPEN_PWM="${CH10_OPEN_PWM:-1300}"
CH10_CLOSE_PWM="${CH10_CLOSE_PWM:-1700}"
FORCE_OPEN_BELOW_Z="${FORCE_OPEN_BELOW_Z:-disabled}"
FORCE_OPEN_BELOW_Z_GRACE_S="${FORCE_OPEN_BELOW_Z_GRACE_S:-2.0}"
POSE_TIMEOUT_S="${POSE_TIMEOUT_S:-1.5}"

TARGET_OFFSET_X_WAS_SET="${TARGET_OFFSET_X+x}"
TARGET_OFFSET_X="${TARGET_OFFSET_X:--0.02}"
TARGET_OFFSET_Y="${TARGET_OFFSET_Y:-0.0}"
TARGET_OFFSET_Z="${TARGET_OFFSET_Z:-0.0}"
TARGET_GRASP_X_BIAS_WAS_SET="${TARGET_GRASP_X_BIAS_M+x}"
TARGET_GRASP_X_BIAS_M="${TARGET_GRASP_X_BIAS_M:--0.02}"
TARGET_PREHOVER_MAP_X_BIAS_WAS_SET="${TARGET_PREHOVER_MAP_X_BIAS_M+x}"
TARGET_PREHOVER_MAP_X_BIAS_M="${TARGET_PREHOVER_MAP_X_BIAS_M:--0.15}"
TARGET_HOVER_MAP_X_BIAS_WAS_SET="${TARGET_HOVER_MAP_X_BIAS_M+x}"
TARGET_HOVER_MAP_X_BIAS_M="${TARGET_HOVER_MAP_X_BIAS_M:-0.0}"
TARGET_GRASP_MAP_X_BIAS_WAS_SET="${TARGET_GRASP_MAP_X_BIAS_M+x}"
TARGET_GRASP_MAP_X_BIAS_M="${TARGET_GRASP_MAP_X_BIAS_M:-0.0}"
BOX_OFFSET_X="${BOX_OFFSET_X:-0.0}"
BOX_OFFSET_Y="${BOX_OFFSET_Y:-0.0}"
BOX_OFFSET_Z="${BOX_OFFSET_Z:-0.0}"
TARGET_HOVER_Z_OFFSET="${TARGET_HOVER_Z_OFFSET:-}"
TARGET_GRASP_Z_OFFSET="${TARGET_GRASP_Z_OFFSET:-}"
TARGET_GRASP_Z_BIAS_M="${TARGET_GRASP_Z_BIAS_M:-0.0}"
BOX_HOVER_Z_OFFSET="${BOX_HOVER_Z_OFFSET:-}"
BOX_PLACE_Z_OFFSET="${BOX_PLACE_Z_OFFSET:-}"
TRANSFER_DRONE_Z_M="${TRANSFER_DRONE_Z_M:-}"
BOX_PLACE_BOTTOM_CLEARANCE_M="${BOX_PLACE_BOTTOM_CLEARANCE_M:-0.24}"

MAX_SPEED="${MAX_SPEED:-0.30}"
APPROACH_SPEED="${APPROACH_SPEED:-0.05}"
LIFT_SPEED="${LIFT_SPEED:-0.10}"
PAYLOAD_LIFT_SPEED="${PAYLOAD_LIFT_SPEED:-0.10}"
PAYLOAD_TRANSFER_SPEED="${PAYLOAD_TRANSFER_SPEED:-0.30}"
GRIPPER_X_OFFSET_M="${GRIPPER_X_OFFSET_M:-0.0}"
GRIPPER_Y_OFFSET_M="${GRIPPER_Y_OFFSET_M:-0.0}"
GRIPPER_Z_OFFSET_M="${GRIPPER_Z_OFFSET_M:-0.25}"
POST_GRASP_SETTLE_S="${POST_GRASP_SETTLE_S:-0.10}"
POST_LIFT_SETTLE_S="${POST_LIFT_SETTLE_S:-0.10}"

WAYPOINT_ARRIVAL_TOLERANCE_M="${WAYPOINT_ARRIVAL_TOLERANCE_M:-0.06}"
WAYPOINT_ARRIVAL_XY_TOLERANCE_M="${WAYPOINT_ARRIVAL_XY_TOLERANCE_M:-0.06}"
WAYPOINT_ARRIVAL_Z_TOLERANCE_M="${WAYPOINT_ARRIVAL_Z_TOLERANCE_M:-0.04}"
TARGET_ARRIVAL_XY_TOLERANCE_M="${TARGET_ARRIVAL_XY_TOLERANCE_M:-0.035}"
TARGET_ARRIVAL_Z_TOLERANCE_M="${TARGET_ARRIVAL_Z_TOLERANCE_M:-0.035}"
TARGET_ARRIVAL_MAX_POSITIVE_X_ERROR_M="${TARGET_ARRIVAL_MAX_POSITIVE_X_ERROR_M:-0.020}"
BOX_ARRIVAL_XY_TOLERANCE_M="${BOX_ARRIVAL_XY_TOLERANCE_M:-0.15}"
BOX_ARRIVAL_Z_TOLERANCE_M="${BOX_ARRIVAL_Z_TOLERANCE_M:-0.10}"
PREGRASP_ARRIVAL_XY_TOLERANCE_M="${PREGRASP_ARRIVAL_XY_TOLERANCE_M:-0.070}"
PREGRASP_ARRIVAL_Z_TOLERANCE_M="${PREGRASP_ARRIVAL_Z_TOLERANCE_M:-0.060}"
PREGRASP_Z_SPEED_MPS="${PREGRASP_Z_SPEED_MPS:-0.10}"
WAYPOINT_ARRIVAL_SETTLE_S="${WAYPOINT_ARRIVAL_SETTLE_S:-0.4}"
TARGET_ARRIVAL_SETTLE_S="${TARGET_ARRIVAL_SETTLE_S:-0.05}"
PREGRASP_ARRIVAL_SETTLE_S="${PREGRASP_ARRIVAL_SETTLE_S:-0.05}"
BOX_ARRIVAL_SETTLE_S="${BOX_ARRIVAL_SETTLE_S:-0.0}"
WAYPOINT_ARRIVAL_TIMEOUT_S="${WAYPOINT_ARRIVAL_TIMEOUT_S:-30.0}"
MOCAP_CORRECTION_ENABLE="${MOCAP_CORRECTION_ENABLE:-false}"
MOCAP_CORRECTION_MAX_XY_M="${MOCAP_CORRECTION_MAX_XY_M:-0.25}"
MOCAP_CORRECTION_MAX_Z_M="${MOCAP_CORRECTION_MAX_Z_M:-0.15}"
MOCAP_CORRECTION_VXY_MPS="${MOCAP_CORRECTION_VXY_MPS:-0.08}"
MOCAP_CORRECTION_VZ_MPS="${MOCAP_CORRECTION_VZ_MPS:-0.04}"
MOCAP_CORRECTION_HLS_XY_VMAX_MPS="${MOCAP_CORRECTION_HLS_XY_VMAX_MPS:-0.02}"
MOCAP_CORRECTION_FREEZE_Z_ON_CONTACT="${MOCAP_CORRECTION_FREEZE_Z_ON_CONTACT:-true}"
MOCAP_CORRECTION_BODY_FRAME="${MOCAP_CORRECTION_BODY_FRAME:-true}"
BODY_FRAME_YAW_SOURCE="${BODY_FRAME_YAW_SOURCE:-drone_control}"
BODY_FRAME_YAW_OFFSET_RAD="${BODY_FRAME_YAW_OFFSET_RAD:-0.0}"
TARGET_YAW_ALIGN_ENABLE="${TARGET_YAW_ALIGN_ENABLE:-true}"
TARGET_YAW_ALIGN_OFFSET_RAD="${TARGET_YAW_ALIGN_OFFSET_RAD:-0.0}"
TARGET_YAW_ALIGN_RATE_DPS="${TARGET_YAW_ALIGN_RATE_DPS:-30.0}"
TARGET_YAW_ALIGN_TOL_DEG="${TARGET_YAW_ALIGN_TOL_DEG:-12.0}"
TARGET_YAW_ALIGN_MIN_DISTANCE_M="${TARGET_YAW_ALIGN_MIN_DISTANCE_M:-0.20}"
TARGET_YAW_ALIGN_MAX_DURATION_S="${TARGET_YAW_ALIGN_MAX_DURATION_S:-5.0}"
CENTER_DEADBAND_M="${CENTER_DEADBAND_M:-0.03}"
CENTER_KP="${CENTER_KP:-1.2}"
CENTER_VMAX_MPS="${CENTER_VMAX_MPS:-0.10}"
CENTER_OFFSET_MAX_M="${CENTER_OFFSET_MAX_M:-0.30}"
HLS_OFFSET_LIMIT_GRACE_S="${HLS_OFFSET_LIMIT_GRACE_S:-5.0}"
HLS_GRASP_TIMEOUT_S="${HLS_GRASP_TIMEOUT_S:-25.0}"
HLS_CENTER_DEADBAND_M="${HLS_CENTER_DEADBAND_M:-0.03}"
HLS_STATUS_CENTER_MISMATCH_TOL_M="${HLS_STATUS_CENTER_MISMATCH_TOL_M:-0.015}"
HLS_GRASP_MAX_RETRIES="${HLS_GRASP_MAX_RETRIES:-2}"
PRE_GRASP_HOLD_S="${PRE_GRASP_HOLD_S:-0.05}"
RELEASE_AT_BOX_HOVER="${RELEASE_AT_BOX_HOVER:-true}"
POST_TAKEOFF_SETTLE_S="${POST_TAKEOFF_SETTLE_S:-2.0}"
LANDING_MODE="${LANDING_MODE:-cmd}"
CMD_LAND_Z="${CMD_LAND_Z:--0.3}"
CMD_LAND_SPEED="${CMD_LAND_SPEED:-0.25}"
COMMAND_STOP_BEFORE_LAND_S="${COMMAND_STOP_BEFORE_LAND_S:-1.2}"
AUTO_LAND_TIMEOUT_S="${AUTO_LAND_TIMEOUT_S:-45.0}"
RELEASE_RETREAT_UP_M="${RELEASE_RETREAT_UP_M:-0.3}"
RELEASE_RETREAT_FORWARD_M="${RELEASE_RETREAT_FORWARD_M:-1.0}"
RELEASE_RETREAT_FRAME="${RELEASE_RETREAT_FRAME:-body_forward}"
NO_LAND="${NO_LAND:-false}"
ENABLE_RECORD="${ENABLE_RECORD:-false}"
RECORD_STATUS_TOPIC="${RECORD_STATUS_TOPIC:-/lerobot_record/status}"
RECORD_GATE_TOPIC="${RECORD_GATE_TOPIC:-/auto_hls_grasp_place/record_gate}"
RECORD_GATE_VALUE="${RECORD_GATE_VALUE:-START}"
RECORD_STOP_TOPIC="${RECORD_STOP_TOPIC:-/auto_hls_grasp_place/record_stop}"
RECORD_STOP_VALUE="${RECORD_STOP_VALUE:-STOP}"
RECORD_STOP_HOLD_S="${RECORD_STOP_HOLD_S:-3.0}"
RECORD_READY_TIMEOUT_S="${RECORD_READY_TIMEOUT_S:-60.0}"
RECORD_DURATION_S="${RECORD_DURATION_S:-${EPISODE_TIME_S:-30}}"
RECORD_START_HOLD_S="${RECORD_START_HOLD_S:-0.06}"

STACK_PID=""
AUTO_STATUS=0

bool_is_true() {
  case "${1,,}" in
    1|true|yes|y|on) return 0 ;;
    *) return 1 ;;
  esac
}

if bool_is_true "${TRAJ_PLANNER_ENABLE}"; then
  if [[ -z "${TARGET_OFFSET_X_WAS_SET}" ]]; then
    TARGET_OFFSET_X="0.0"
  fi
  if [[ "${CMD_TOPIC}" == "/position_cmd" ]]; then
    CMD_TOPIC="${TRAJ_PLANNER_INPUT_TOPIC}"
  fi
  PX4CTRL_TD_ENABLE="${PX4CTRL_TD_ENABLE:-false}"
  PX4CTRL_CMD_FEEDFORWARD_ENABLE="${PX4CTRL_CMD_FEEDFORWARD_ENABLE:-true}"
  if [[ -z "${TARGET_GRASP_X_BIAS_WAS_SET}" ]]; then
    TARGET_GRASP_X_BIAS_M="0.0"
  fi
  if [[ -z "${TARGET_PREHOVER_MAP_X_BIAS_WAS_SET}" ]]; then
    TARGET_PREHOVER_MAP_X_BIAS_M="-0.16"
  fi
  if [[ -z "${TARGET_HOVER_MAP_X_BIAS_WAS_SET}" ]]; then
    TARGET_HOVER_MAP_X_BIAS_M="-0.06"
  fi
  if [[ -z "${TARGET_GRASP_MAP_X_BIAS_WAS_SET}" ]]; then
    TARGET_GRASP_MAP_X_BIAS_M="-0.06"
  fi
fi

cleanup_stack() {
  if [[ -z "${STACK_PID}" ]]; then
    return
  fi
  if bool_is_true "${CLEANUP_STACK_ON_EXIT}"; then
    echo "[auto-hls-ude-test] stopping mocap/MAVROS/bridge/px4ctrl stack"
    kill -TERM -- "-${STACK_PID}" 2>/dev/null || kill -TERM "${STACK_PID}" 2>/dev/null || true
    local deadline=$((SECONDS + ${STACK_CLEANUP_TIMEOUT_S%.*}))
    while (( SECONDS < deadline )); do
      if ! kill -0 -- "-${STACK_PID}" 2>/dev/null && ! kill -0 "${STACK_PID}" 2>/dev/null; then
        STACK_PID=""
        return
      fi
      sleep 0.1
    done
    kill -KILL -- "-${STACK_PID}" 2>/dev/null || kill -KILL "${STACK_PID}" 2>/dev/null || true
    wait "${STACK_PID}" 2>/dev/null || true
    STACK_PID=""
  else
    echo "[auto-hls-ude-test] leaving stack running. Stop it later with: kill -TERM -- -${STACK_PID}"
  fi
}

on_interrupt() {
  echo
  if bool_is_true "${KEEP_STACK_ON_INTERRUPT}"; then
    echo "[auto-hls-ude-test] interrupted; leaving stack running because KEEP_STACK_ON_INTERRUPT=true"
    CLEANUP_STACK_ON_EXIT="false"
  else
    echo "[auto-hls-ude-test] interrupted; stopping stack"
    CLEANUP_STACK_ON_EXIT="true"
  fi
  AUTO_STATUS=130
  exit 130
}

run_preflight_pass() {
  echo "[auto-hls-ude-test] checking required topics in parallel"
  PYTHONNOUSERSITE=1 "${PREFLIGHT_PYTHON}" "${PREFLIGHT_CHECKER}" \
    --timeout "${POSE_PREFLIGHT_TIMEOUT_S}" \
    --log-prefix "[auto-hls-ude-test]" \
    --status-log-period "${PREFLIGHT_STATUS_LOG_PERIOD_S}" \
    --topic "control drone pose:${DRONE_POSE_TOPIC}:nav_msgs/msg/Odometry" \
    --topic "arrival check pose:${ARRIVAL_POSE_TOPIC}:geometry_msgs/msg/PoseStamped" \
    --topic "target pose:${TARGET_POSE_TOPIC}:geometry_msgs/msg/PoseStamped" \
    --topic "box pose:${BOX_POSE_TOPIC}:geometry_msgs/msg/PoseStamped" \
    --topic "RC input:${RC_TOPIC}:mavros_msgs/msg/RCIn" \
    --topic "px4ctrl state:${PX4CTRL_STATE_TOPIC}:std_msgs/msg/String" \
    --topic "MAVROS state:${MAVROS_STATE_TOPIC}:mavros_msgs/msg/State"
}

trap on_interrupt INT TERM
trap cleanup_stack EXIT

set +u
if [[ -f /opt/ros/humble/setup.bash ]]; then
  # shellcheck source=/opt/ros/humble/setup.bash
  source /opt/ros/humble/setup.bash
fi
if [[ -f "${WORKSPACE_DIR}/install/setup.bash" ]]; then
  # shellcheck source=/dev/null
  source "${WORKSPACE_DIR}/install/setup.bash"
else
  set -u
  echo "[auto-hls-ude-test] ERROR: ${WORKSPACE_DIR}/install/setup.bash not found" >&2
  echo "[auto-hls-ude-test] build first with: colcon build" >&2
  exit 1
fi
set -u

echo "[auto-hls-ude-test] workspace: ${WORKSPACE_DIR}"
echo "[auto-hls-ude-test] drone vrpn: ${VRPN_SOURCE_TOPIC} -> ${MAVROS_VISION_TOPIC}"
echo "[auto-hls-ude-test] control drone pose topic: ${DRONE_POSE_TOPIC}"
echo "[auto-hls-ude-test] arrival check pose topic: ${ARRIVAL_POSE_TOPIC}"
echo "[auto-hls-ude-test] target topic: ${TARGET_POSE_TOPIC}"
echo "[auto-hls-ude-test] box topic: ${BOX_POSE_TOPIC}"
echo "[auto-hls-ude-test] landing: mode=${LANDING_MODE} cmd_z=${CMD_LAND_Z} cmd_speed=${CMD_LAND_SPEED} command_stop_before_land=${COMMAND_STOP_BEFORE_LAND_S}s auto_land_timeout=${AUTO_LAND_TIMEOUT_S}s no_land=${NO_LAND}"
echo "[auto-hls-ude-test] CH10 safety: topic=${RC_TOPIC} timeout=${RC_TIMEOUT_S}s stale_action=${RC_STALE_ACTION} index=${CH10_INDEX} open<=${CH10_OPEN_PWM} force_open_below_z=${FORCE_OPEN_BELOW_Z} low_z_grace=${FORCE_OPEN_BELOW_Z_GRACE_S}s"
echo "[auto-hls-ude-test] offsets: target=(${TARGET_OFFSET_X}, ${TARGET_OFFSET_Y}, ${TARGET_OFFSET_Z}) box=(${BOX_OFFSET_X}, ${BOX_OFFSET_Y}, ${BOX_OFFSET_Z})"
echo "[auto-hls-ude-test] grasp body bias: target_grasp_x_bias=${TARGET_GRASP_X_BIAS_M}m target_grasp_z_bias=${TARGET_GRASP_Z_BIAS_M}m"
echo "[auto-hls-ude-test] trajectory planner: enable=${TRAJ_PLANNER_ENABLE} raw=${TRAJ_PLANNER_INPUT_TOPIC} traj=${TRAJ_PLANNER_OUTPUT_TOPIC}"
echo "[auto-hls-ude-test] target map-X bias: prehover=${TARGET_PREHOVER_MAP_X_BIAS_M}m hover=${TARGET_HOVER_MAP_X_BIAS_M}m grasp=${TARGET_GRASP_MAP_X_BIAS_M}m"
echo "[auto-hls-ude-test] grasp z: target_grasp_z_offset=${TARGET_GRASP_Z_OFFSET:-<auto>} target_grasp_z_bias=${TARGET_GRASP_Z_BIAS_M} transfer_z=${TRANSFER_DRONE_Z_M:-<auto>}"
echo "[auto-hls-ude-test] motion speed: max=${MAX_SPEED} approach=${APPROACH_SPEED} lift=${LIFT_SPEED} payload_lift=${PAYLOAD_LIFT_SPEED} payload_transfer=${PAYLOAD_TRANSFER_SPEED} pre_grasp_hold=${PRE_GRASP_HOLD_S}s post_grasp=${POST_GRASP_SETTLE_S}s post_lift=${POST_LIFT_SETTLE_S}s"
echo "[auto-hls-ude-test] release retreat: up=${RELEASE_RETREAT_UP_M} forward=${RELEASE_RETREAT_FORWARD_M} frame=${RELEASE_RETREAT_FRAME}"
echo "[auto-hls-ude-test] arrival gates: waypoint_xy=${WAYPOINT_ARRIVAL_XY_TOLERANCE_M} waypoint_z=${WAYPOINT_ARRIVAL_Z_TOLERANCE_M} target_xy=${TARGET_ARRIVAL_XY_TOLERANCE_M} target_z=${TARGET_ARRIVAL_Z_TOLERANCE_M} target_max_positive_x=${TARGET_ARRIVAL_MAX_POSITIVE_X_ERROR_M} pregrasp_xy=${PREGRASP_ARRIVAL_XY_TOLERANCE_M} pregrasp_z=${PREGRASP_ARRIVAL_Z_TOLERANCE_M} box_xy=${BOX_ARRIVAL_XY_TOLERANCE_M} box_z=${BOX_ARRIVAL_Z_TOLERANCE_M} settle_default=${WAYPOINT_ARRIVAL_SETTLE_S} target_settle=${TARGET_ARRIVAL_SETTLE_S} pregrasp_settle=${PREGRASP_ARRIVAL_SETTLE_S} box_settle=${BOX_ARRIVAL_SETTLE_S} pregrasp_z_speed=${PREGRASP_Z_SPEED_MPS}"
echo "[auto-hls-ude-test] release timing: release_at_box_hover=${RELEASE_AT_BOX_HOVER}"
echo "[auto-hls-ude-test] mocap correction: enable=${MOCAP_CORRECTION_ENABLE} max_xy=${MOCAP_CORRECTION_MAX_XY_M} max_z=${MOCAP_CORRECTION_MAX_Z_M} vxy=${MOCAP_CORRECTION_VXY_MPS} vz=${MOCAP_CORRECTION_VZ_MPS} hls_xy_vmax=${MOCAP_CORRECTION_HLS_XY_VMAX_MPS} freeze_z_on_contact=${MOCAP_CORRECTION_FREEZE_Z_ON_CONTACT} body_frame=${MOCAP_CORRECTION_BODY_FRAME} yaw_source=${BODY_FRAME_YAW_SOURCE} yaw_offset_rad=${BODY_FRAME_YAW_OFFSET_RAD}"
echo "[auto-hls-ude-test] target yaw align: enable=${TARGET_YAW_ALIGN_ENABLE} offset=${TARGET_YAW_ALIGN_OFFSET_RAD}rad rate=${TARGET_YAW_ALIGN_RATE_DPS}deg/s tol=${TARGET_YAW_ALIGN_TOL_DEG}deg min_distance=${TARGET_YAW_ALIGN_MIN_DISTANCE_M}m max_duration=${TARGET_YAW_ALIGN_MAX_DURATION_S}s"
echo "[auto-hls-ude-test] hls centering assist: center_kp=${CENTER_KP} center_vmax=${CENTER_VMAX_MPS} center_offset_max=${CENTER_OFFSET_MAX_M} center_deadband=${CENTER_DEADBAND_M} hls_deadband=${HLS_CENTER_DEADBAND_M} limit_grace=${HLS_OFFSET_LIMIT_GRACE_S}s grasp_timeout=${HLS_GRASP_TIMEOUT_S}s snapshot_mismatch_tol=${HLS_STATUS_CENTER_MISMATCH_TOL_M}"
echo "[auto-hls-ude-test] hls manager startup timeout: ${HLS_MANAGER_STARTUP_TIMEOUT_S}s"
echo "[auto-hls-ude-test] hls grasp retries: ${HLS_GRASP_MAX_RETRIES}"
echo "[auto-hls-ude-test] takeoff: mode=${TAKEOFF_MODE} inner_confirm=${CONFIRM_BEFORE_TAKEOFF} outer_wait=${WAIT_FOR_ENTER}"
echo "[auto-hls-ude-test] px4ctrl gripper rc channel override: ${PX4CTRL_GRIPPER_RC_CHANNEL}"
echo "[auto-hls-ude-test] px4ctrl takeoff speed override: ${PX4CTRL_TAKEOFF_LAND_SPEED} m/s"
echo "[auto-hls-ude-test] px4ctrl takeoff height override: ${PX4CTRL_TAKEOFF_HEIGHT:-<yaml-default>} m"
echo "[auto-hls-ude-test] record gate: enable=${ENABLE_RECORD} status=${RECORD_STATUS_TOPIC} gate=${RECORD_GATE_TOPIC} value=${RECORD_GATE_VALUE} stop=${RECORD_STOP_TOPIC} stop_value=${RECORD_STOP_VALUE} duration=${RECORD_DURATION_S}s"
echo "[auto-hls-ude-test] preflight checker: ${PREFLIGHT_PYTHON} ${PREFLIGHT_CHECKER}"
echo "[auto-hls-ude-test] preflight status log period: ${PREFLIGHT_STATUS_LOG_PERIOD_S}s"

if bool_is_true "${START_STACK}"; then
  echo "[auto-hls-ude-test] starting mocap/MAVROS/bridge/px4ctrl stack"
  export START_PX4CTRL
  export PX4CTRL_GRIPPER_RC_CHANNEL
  export PX4CTRL_TAKEOFF_LAND_SPEED
  export PX4CTRL_TAKEOFF_HEIGHT
  export PX4CTRL_UDE_ENABLE
  export PX4CTRL_TD_ENABLE
  export PX4CTRL_CMD_FEEDFORWARD_ENABLE
  export PX4CTRL_ATTITUDE_FEEDBACK_MODE
  export TRAJ_PLANNER_ENABLE TRAJ_PLANNER_INPUT_TOPIC TRAJ_PLANNER_OUTPUT_TOPIC TRAJ_PLANNER_RATE_HZ
  export TRAJ_PLANNER_MAX_SPEED_XY_MPS TRAJ_PLANNER_MAX_ACCEL_XY_MPS2 TRAJ_PLANNER_MAX_SPEED_Z_MPS TRAJ_PLANNER_MAX_ACCEL_Z_MPS2
  export TRAJ_PLANNER_CENTERING_MAX_SPEED_XY_MPS TRAJ_PLANNER_CENTERING_MAX_ACCEL_XY_MPS2
  export TRAJ_PLANNER_MAX_YAW_RATE_RADPS TRAJ_PLANNER_MAX_YAW_ACCEL_RADPS2
  export TRAJ_PLANNER_GOAL_REPLAN_POS_THRESHOLD_M TRAJ_PLANNER_GOAL_REPLAN_YAW_THRESHOLD_RAD TRAJ_PLANNER_GOAL_STALE_TIMEOUT_S
  export TRAJ_PLANNER_DURATION_SCALE
  export VRPN_SOURCE_TOPIC
  export MAVROS_VISION_TOPIC
	  setsid bash "${SCRIPT_DIR}/run_mocap_mavros.sh" &
	  STACK_PID="$!"
	  echo "[auto-hls-ude-test] stack process group: ${STACK_PID}"
	  if [[ -n "${STACK_PID_FILE}" ]]; then
	    printf '%s\n' "${STACK_PID}" > "${STACK_PID_FILE}"
	  fi
	  sleep "${STACK_STARTUP_WAIT_S}"
else
  echo "[auto-hls-ude-test] START_STACK=false; using already-running stack"
fi

if ! bool_is_true "${SKIP_POSE_PREFLIGHT}"; then
  preflight_ok=false
  for ((attempt = 1; attempt <= POSE_PREFLIGHT_RETRIES; attempt++)); do
    echo "[auto-hls-ude-test] preflight topic check attempt ${attempt}/${POSE_PREFLIGHT_RETRIES}"
    if run_preflight_pass; then
      preflight_ok=true
      break
    fi
    if (( attempt < POSE_PREFLIGHT_RETRIES )); then
      echo "[auto-hls-ude-test] preflight did not see every required topic; retrying after 1s." >&2
      sleep 1
    fi
  done
  if [[ "${preflight_ok}" != "true" ]]; then
    echo "[auto-hls-ude-test] Preflight did not see every required topic after ${POSE_PREFLIGHT_RETRIES} attempt(s)." >&2
    if bool_is_true "${POSE_PREFLIGHT_REQUIRED}"; then
      exit 1
    fi
  fi
fi

if bool_is_true "${WAIT_FOR_ENTER}"; then
  echo
  echo "[auto-hls-ude-test] Keep RC in hover+command mode, sticks centered, CH10 not low/open."
  echo "[auto-hls-ude-test] Press Enter to start preflight pose locking. A second inner confirmation may be used before TAKEOFF."
  read -r _
fi

export TARGET_POSE_TOPIC BOX_POSE_TOPIC DRONE_POSE_TOPIC ARRIVAL_POSE_TOPIC CMD_TOPIC RC_TOPIC RC_TIMEOUT_S RC_STALE_ACTION
export MAVROS_STATE_TOPIC
export CH10_INDEX CH10_OPEN_PWM CH10_CLOSE_PWM FORCE_OPEN_BELOW_Z FORCE_OPEN_BELOW_Z_GRACE_S POSE_TIMEOUT_S
export GRIPPER_MANAGER_PORT HLS_GRAVITY_COMP_PATH HLS_MOTION_PROFILE
export HLS_SEARCH_SPEED HLS_SEARCH_ACC HLS_SEARCH_TORQUE_LIMIT
export HLS_LEFT_CURRENT_INWARD_SIGN HLS_RIGHT_CURRENT_INWARD_SIGN
export HLS_OPEN_TORQUE_LIMIT HLS_LOW_CURRENT HLS_CENTER_HOLD_CURRENT HLS_CENTER_PUSH_CURRENT HLS_GRIP_CHASE_MIN_CURRENT HLS_LIFT_CURRENT HLS_MAX_CURRENT
export HLS_GRIP_CHASE_POSITION_ENABLE HLS_GRIP_CHASE_POSITION_SPEED HLS_GRIP_CHASE_POSITION_ACC
export HLS_GRIP_CHASE_POSITION_TORQUE_LIMIT HLS_GRIP_CHASE_SLIP_RATIO HLS_GRIP_CHASE_POSITION_PERIOD_S
export HLS_GRIP_CHASE_POSITION_PULSE_S HLS_CENTER_TIMEOUT_ACTION HLS_CENTER_TIMEOUT_S HLS_CENTER_STABLE_TIME_S HLS_FINAL_GRIP_RAMP_S HLS_CENTER_ERROR_GAIN HLS_CENTER_DEADBAND_M
export HLS_CONTACT_CURRENT_THRESHOLD HLS_CONTACT_EXIT_THRESHOLD HLS_CONTACT_STRONG_THRESHOLD HLS_CONTACT_CONFIRM_CYCLES
export HLS_SEARCH_CONTACT_CURRENT_THRESHOLD HLS_SEARCH_CONTACT_STRONG_THRESHOLD HLS_SEARCH_CONTACT_CONFIRM_CYCLES HLS_SEARCH_CONTACT_MIN_CLOSE_RATIO
export HLS_SINGLE_CONTACT_OFFSET_LIMIT_M HLS_MANAGER_STARTUP_TIMEOUT_S
export TRAJ_PLANNER_ENABLE TRAJ_PLANNER_INPUT_TOPIC TRAJ_PLANNER_OUTPUT_TOPIC
export TARGET_OFFSET_X TARGET_OFFSET_Y TARGET_OFFSET_Z TARGET_GRASP_X_BIAS_M TARGET_PREHOVER_MAP_X_BIAS_M TARGET_HOVER_MAP_X_BIAS_M TARGET_GRASP_MAP_X_BIAS_M BOX_OFFSET_X BOX_OFFSET_Y BOX_OFFSET_Z
export TARGET_HOVER_Z_OFFSET TARGET_GRASP_Z_OFFSET TARGET_GRASP_Z_BIAS_M BOX_HOVER_Z_OFFSET BOX_PLACE_Z_OFFSET TRANSFER_DRONE_Z_M BOX_PLACE_BOTTOM_CLEARANCE_M
export MAX_SPEED APPROACH_SPEED LIFT_SPEED PAYLOAD_LIFT_SPEED PAYLOAD_TRANSFER_SPEED POST_GRASP_SETTLE_S POST_LIFT_SETTLE_S PRE_GRASP_HOLD_S RELEASE_AT_BOX_HOVER
export GRIPPER_X_OFFSET_M GRIPPER_Y_OFFSET_M GRIPPER_Z_OFFSET_M
export WAYPOINT_ARRIVAL_TOLERANCE_M WAYPOINT_ARRIVAL_XY_TOLERANCE_M WAYPOINT_ARRIVAL_Z_TOLERANCE_M
export TARGET_ARRIVAL_XY_TOLERANCE_M TARGET_ARRIVAL_Z_TOLERANCE_M TARGET_ARRIVAL_MAX_POSITIVE_X_ERROR_M BOX_ARRIVAL_XY_TOLERANCE_M BOX_ARRIVAL_Z_TOLERANCE_M
export PREGRASP_ARRIVAL_XY_TOLERANCE_M PREGRASP_ARRIVAL_Z_TOLERANCE_M PREGRASP_Z_SPEED_MPS
export WAYPOINT_ARRIVAL_SETTLE_S TARGET_ARRIVAL_SETTLE_S PREGRASP_ARRIVAL_SETTLE_S BOX_ARRIVAL_SETTLE_S WAYPOINT_ARRIVAL_TIMEOUT_S POST_TAKEOFF_SETTLE_S
export MOCAP_CORRECTION_ENABLE MOCAP_CORRECTION_MAX_XY_M MOCAP_CORRECTION_MAX_Z_M
export MOCAP_CORRECTION_VXY_MPS MOCAP_CORRECTION_VZ_MPS MOCAP_CORRECTION_HLS_XY_VMAX_MPS
export MOCAP_CORRECTION_FREEZE_Z_ON_CONTACT MOCAP_CORRECTION_BODY_FRAME BODY_FRAME_YAW_SOURCE BODY_FRAME_YAW_OFFSET_RAD
export TARGET_YAW_ALIGN_ENABLE TARGET_YAW_ALIGN_OFFSET_RAD TARGET_YAW_ALIGN_RATE_DPS
export TARGET_YAW_ALIGN_TOL_DEG TARGET_YAW_ALIGN_MIN_DISTANCE_M TARGET_YAW_ALIGN_MAX_DURATION_S
export CENTER_DEADBAND_M CENTER_KP CENTER_VMAX_MPS CENTER_OFFSET_MAX_M HLS_OFFSET_LIMIT_GRACE_S HLS_GRASP_TIMEOUT_S HLS_STATUS_CENTER_MISMATCH_TOL_M HLS_GRASP_MAX_RETRIES
export CONFIRM_BEFORE_TAKEOFF TAKEOFF_MODE
export LANDING_MODE CMD_LAND_Z CMD_LAND_SPEED COMMAND_STOP_BEFORE_LAND_S AUTO_LAND_TIMEOUT_S RELEASE_RETREAT_UP_M RELEASE_RETREAT_FORWARD_M RELEASE_RETREAT_FRAME NO_LAND POSE_PREFLIGHT_REQUIRED SKIP_POSE_PREFLIGHT POSE_PREFLIGHT_TIMEOUT_S POSE_PREFLIGHT_RETRIES
export POST_RELEASE_HOLD_STOP_S
export PREFLIGHT_STATUS_LOG_PERIOD_S
export ENABLE_RECORD RECORD_STATUS_TOPIC RECORD_GATE_TOPIC RECORD_GATE_VALUE RECORD_STOP_TOPIC RECORD_STOP_VALUE RECORD_STOP_HOLD_S RECORD_READY_TIMEOUT_S RECORD_DURATION_S RECORD_START_HOLD_S

set +e
bash "${SCRIPT_DIR}/auto_hls_grasp_place.sh"
AUTO_STATUS="$?"
set -e

exit "${AUTO_STATUS}"
